# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: 2248392717@qq.com
author_name: Evan
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: rate_cell
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: rate_cell
repository: ''
test: true
viewer_name: ''

